FeedBackSystem/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using FeedBackSystem.Domain.RepositoryInterface;
using FeedBackSystem.Model.DtoModels;
using FeedBackSystem.BussinessLogicLayer.Service;
using FeedBackSystem.Domain.ServiceInterface;

namespace FeedBackSystem.Controllers
{
    [Authorize(Roles = "superadmin")]
    public class BaseController : Controller
    { 

      
        readonly IFeedBackBussiness  service;
        readonly IAddTitleAndQuestions  repository;

        //inject dependency
        public BaseController(IFeedBackBussiness service, IAddTitleAndQuestions repository)
        {
            this.repository = repository;
            this.service = service;
      
        }
        public void Index()
        {
            try
            {
                int x, y, z;
                x = 5; y = 0;
                z = x / y;
            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                var log = new CreateLog();
                log.GlobalPropertiesOfContAndMethodName(ex, actionName, controllerName);
            }

        }
        
        public ActionResult MasterPage()
        {
            return View();
        }

        public JsonResult SaveCompany(string txt1)
        {
            return Json(service.SaveCompanyFromBase(txt1,  repository),  JsonRequestBehavior.AllowGet);
        }

        public ActionResult AssignRolesToUsers()
        {
            return View();
        }

        public JsonResult GetAllUsers1()
        {
            return Json(service.GetAllUsers1FromBase(repository), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllRoles()
        {
            return Json(service.GetAllRolesFromBase(repository), JsonRequestBehavior.AllowGet);
        }

        public JsonResult SaveSelectedUsers1(List<AssignedTitles> list1)
        {
            return Json(service.SaveSelectedUsers1FromBase(list1, repository), JsonRequestBehavior.AllowGet);
        }

        public ActionResult AssignUsersToCompany()
        {
            return View();
        }

        public async Task<JsonResult> GetAllUsers2()
        {
            return Json(await service.GetAllUsers2FromBase(repository), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllAdmin()
        {
            return Json(service.GetAllAdminFromBase(repository), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllCompany()
        {
            return Json(service.GetAllCompanyFromBase(repository), JsonRequestBehavior.AllowGet);
        }

        public JsonResult AssignCompany(List<AssignedTitles> list)
        {
            return Json(service.AssignCompanyFromBase(list, repository), JsonRequestBehavior.AllowGet);
        }

    }
}

FeedBackSystem/Views/Base/AssignRolesToUsers.cshtml
@{
    ViewBag.Title = "AssignRolesToUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    <title></title>
    <style>

        .scroll {
            overflow: auto;
            height: auto;
        }

        ol {
            list-style-type: none;
            width: 170px;
            height: 480px;
        }

        .k li {
            height: 30px;
            width: 150px;
            border: 1px solid white;
            margin: 2px;
            font-size: 20px;
            text-align: center;
        }

        #Users li {
            background-color: lightgreen;
        }

        #Roles li {
            background-color: lightgreen;
        }

        fieldset {
            float: left;
            margin: 30px;
            width: 200px;
            height: 500px;
            border: 1px solid black;
        }

        #b button {
            width: 141px;
            height: 34px;
            background-color: #5cb85c;
            border-radius: 8px;
        }


        form label {
            display: inline-block;
            width: 100px;
        }


        .error {
            color: red;
            margin-left: 5px;
        }

        label.error {
            display: inline;
        }
    </style>


    <script>
        $(document).ready(function () {


            $('#Users').sortable({ connectWith: "#SelectedUsers" });
            $('#SelectedUsers').sortable({ connectWith: "#Users" });
            $('#Roles').sortable({ connectWith: "#SelectedRole" });
            $('#SelectedRole').sortable({ connectWith: "#Roles" });

            $.ajax({
                type: "GET",
                url: "/Base/GetAllUsers1",
                success: function (result) {
                    $.template('newData1', '<br><li class="k" id="${UserId}">${User}</li>');
                    $.tmpl('newData1', result).appendTo('#Users');

                }
            })

            $.ajax({
                type: "GET",
                url: "/Base/GetAllRoles",
                success: function (result) {
                    $.template('newData2', '<br><li class="k" id="${RoleId}">${Role}</li>');
                    $.tmpl('newData2', result).appendTo('#Roles');

                }
            })
        });

        function AssignRole()
        {        
                var AssignedRole = new Array();
                $("#f3 ol li").each(function () {
                    var row = $(this);
                    $("#f4 ol li ").each(function () {
                        var title = {};
                        title.UserId = row.attr("id");
                        title.RoleId = $(this).attr("id");
                        AssignedRole.push(title);
                    });

                });

            if (AssignedRole.length < 1)
            {
                    $('#div1').html('<span class="error">please Assign Roles to the Users</span>');
            }
            else if (AssignedRole.length > 1)
            {
                    $('#div1').html('<span class="error">please Assign a single role to User</span>');
            }
            else
            {
                    $(".error").empty();
                    $.ajax({
                        type: "Post",
                        url: "/Base/SaveSelectedUsers1",
                        data: JSON.stringify(AssignedRole),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: function (result)
                        {
                            alert("Successfully assigned.");
                            window.location.href = "/Base/AssignRolesToUsers";
                        }
                    })
            }
        }
    </script>
</head>
<body>
    <div id="div1"></div>

    <fieldset class="scroll" id="f1">
        <legend><b>Users</b></legend>
        <ol id="Users"></ol>
    </fieldset>

    <fieldset class="scroll" id="f2">
        <legend><b>Roles</b></legend>
        <ol id="Roles"></ol>
    </fieldset>
    <fieldset class="scroll" id="f3">
        <legend><b>Selected Users</b></legend>
        <ol id="SelectedUsers"></ol>
    </fieldset>
    <fieldset class="scroll" id="f4">
        <legend><b>Selected Role</b></legend>
        <ol id="SelectedRole"></ol>
    </fieldset>
    <button href="#" onclick="AssignRole()" class="btn btn-success" id="b">Assign </button>
</body>
</html>

FeedBackSystem/Views/Base/AssignUsersToCompany.cshtml
@{
    ViewBag.Title = "AssignUsersToCompany";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<html>
<head>
    <title></title>
    <style>

        .scroll {
            overflow: auto;
            height: auto;
        }

        ol {
            list-style-type: none;
            width: 135px;
            height: 480px;
            padding:0px;
        }


        .k li {
            height: 30px;
            width: 150px;
            border: 1px solid white;
            margin: 2px;
            font-size: 20px;
            text-align: center;
        }

        #Users li {
            background-color: #423B88;
            color:white;
        }

        #Admin li {
            background-color: #423B88;
            color: white;
        }

        #Companies li {
            background-color: #423B88;
            color: white;
            padding: 5px;
        }

        fieldset {
            float: left;
            margin: 30px;
            width: 180px;
            height: 380px;
            border: 1px solid black;
        }

        #b button {
            width: 141px;
            height: 34px;
            background-color: rebeccapurple;
            border-radius: 8px;
            margin-left:55px;
        }
        .btn {
            margin-left: 55px;
            margin-top: 39px;
            padding: 11px;
            width: 110px;
            background-color: #423B88;
        }

        form label {
            display: inline-block;
            width: 100px;
        }


        .error {
            color: red;
            margin-left: 5px;
        }

        label.error {
            display: inline;
        }
        .lgnd
        {
            font-size:11px;
        }
        .select 
        {
            margin:0px;
        }
        b{
            margin:25px;
        }
    </style>


    <script>
        $(document).ready(function () {


            //$('#Users').sortable({ connectWith: "#SelectedUsers" });
            $('#Admin').sortable({ connectWith: "#SelectedUsers" });
            //$('#SelectedUsers').sortable({ connectWith: "#Users" });
            $('#SelectedUsers').sortable({ connectWith: "#Admin" });
            $('#Companies').sortable({ connectWith: "#SelectedCompany" });
            $('#SelectedCompany').sortable({ connectWith: "#Companies" });

            //$.ajax({
            //    type: "GET",
            //    url: "/Base/GetAllUsers2",
            //    success: function (result) {
            //        $.template('newData1', '<br><li class="k" id="${UserId}">${User}</li>');
            //        $.tmpl('newData1', result).appendTo('#Users');

            //    }
            //})

            $.ajax({
                type: "GET",
                url: "/Base/GetAllAdmin",
                success: function (result) {
                    $.template('newData2', '<br><li class="k" id="${UserId}">${User}</li>');
                    $.tmpl('newData2', result).appendTo('#Admin');

                }
            })

            $.ajax({
                type: "GET",
                url: "/Base/GetAllCompany",
                success: function (result) {
                    $.template('newData2', '<br><li class="k" id="${CompanyId}">${Company}</li>');
                    $.tmpl('newData2', result).appendTo('#Companies');

                }
            })
        });

        function AssignRole() {
            var AssignedRole = new Array();
            $("#f4 ol li").each(function () {
                var row = $(this);
                $("#f5 ol li ").each(function () {
                    var title = {};
                    title.UserId = row.attr("id");
                    title.CompanyId = $(this).attr("id");
                    AssignedRole.push(title);
                });

            });

            if (AssignedRole.length < 1) {
                $('#div1').html('<span class="error">please Assign users to the company</span>');
            }
            else if (AssignedRole.length > 1) {
                $('#div1').html('<span class="error">please Assign a single company to Users</span>');
            }
            else {
                $(".error").empty();

                $.ajax({
                    type: "Post",
                    url: "/Base/AssignCompany",
                    data: JSON.stringify(AssignedRole),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (result) {
                        alert("Successfully assigned.");
                        window.location.href = "/Base/AssignUsersToCompany";


                    }
                })
            }

        }
    </script>
</head>
<body>
    <div id="div1"></div>
    <div class="row">
        @*<div class=" col-md-2">
            <fieldset class="scroll" id="f1">
                <legend><b>Users</b></legend>
                <ol id="Users"></ol>
            </fieldset>
        </div>*@
        <div class="col-md-2 ">
            <fieldset class="scroll" id="f2" style="padding:34px;">
                <legend class="lgnd"><b>Admin</b></legend>
                <ol id="Admin"></ol>
            </fieldset>
        </div>
        <div class=" col-md-2 ">
            <fieldset class="scroll" id="f3"style="padding:34px;">
                <legend class="lgnd"><b>Companies</b></legend>
                <ol id="Companies"></ol>
            </fieldset>
        </div>
        <div class=" col-md-2 ">
            <fieldset class="scroll" id="f4"style="padding:34px;">
                <legend class="lgnd"><b class="select">Selected Admin</b></legend>
                <ol id="SelectedUsers"></ol>
            </fieldset>
        </div>
        <div class=" col-md-2">
            <fieldset class="scroll" id="f5"style="padding:34px;">
                <legend class="lgnd"><b class="select">Selected Companies</b></legend>
                <ol id="SelectedCompany"></ol>
            </fieldset>
        </div>
        <div class=" col-md-2">
            <button href="#" onclick="AssignRole()" class="btn btn-success" id="b">Assign </button>
        </div>
    </div> 
    
</body>
</html>

FeedBackSystem/Views/Base/MasterPage.cshtml
@{
    ViewBag.Title = "MasterPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    <style>
        .btn-success {
            color: #fff;
            background-color: #423B88;
            border-color: #423B88;
        }

        #p1 {
            color: black;
            font-family: Bahnschrift;
            font-size: 18px;
        }

        body {
            font-family: Arial;
            font-size: 10pt;
        }

        .table {
            border: 1px solid ridge;
            border-collapse: collapse;
            color: crimson;
        }

            .table th {
                background-color: #F7F7F7;
                color: brown;
                font-weight: bold;
            }

            .table th, .table td {
                padding: 5px;
                border: 1px solid #ccc;
            }

        #txtQuestion {
            max-width: 735px;
        }

        form label {
            display: inline-block;
            width: 100px;
        }

        form div {
            margin-bottom: 1px;
        }

        .error {
            color: red;
            margin-left: 5px;
        }

        label.error {
            display: inline;
        }
        .slide-content {
            padding-top: 180px;
            text-size-adjust: 50%;
            font: 35px Montserrat, sans-serif;
        }
        p:hover {
            animation: shake 0.5s;
            animation-iteration-count: infinite;
        }

        @@-webkit-keyframes shake {
            0% {
                transform: translate(1px, 1px) rotate(0deg);
            }

            10% {
                transform: translate(-1px, -2px) rotate(-1deg);
            }

            20% {
                transform: translate(-3px, 0px) rotate(1deg);
            }

            30% {
                transform: translate(3px, 2px) rotate(0deg);
            }

            40% {
                transform: translate(1px, -1px) rotate(1deg);
            }

            50% {
                transform: translate(-1px, 2px) rotate(-1deg);
            }

            60% {
                transform: translate(-3px, 1px) rotate(0deg);
            }

            70% {
                transform: translate(3px, 1px) rotate(-1deg);
            }

            80% {
                transform: translate(-1px, -1px) rotate(1deg);
            }

            90% {
                transform: translate(1px, 2px) rotate(0deg);
            }

            100% {
                transform: translate(1px, -2px) rotate(-1deg);
            }
        }
    </style>

    <script src="~/Scripts/script.js"></script>
    <link href="~/Content/style.css" rel="stylesheet" />
</head>
<body>

    <br />
    <br />

    <div class="slide_box">
        <ul class="slide_pic">
            <li style="text-align:center;color:#423B88"><p class="slide-content">You can Create a New Company</p></li>
            <li style="text-align:center;color:#423B88"><p class="slide-content">You can Create  New  Administrator's</p></li>
            <li style="text-align:center;color:#423B88"><p class="slide-content">You can Assign Admin to Company </p></li>

        </ul>
        <ul class="slide_tab"></ul>
        <a href="javascript:" class="slide_nav slide_prev" style="color:#423B88">&lt;</a>
        <a href="javascript:" class="slide_nav slide_next" style="color:#423B88">&gt;</a>
    </div>

    <br />
    <br />

    <br />
    <br />

    <br />
    <br />


    <div class="row">

        <br />
        <br />
        <br />
        <br />
        <br />

        <div class="col-md-4">
            <p class="btn btn-" id="p1"><span class="glyphicon glyphicon-share-alt"></span> &nbsp;&nbsp;&nbsp; Click This Button to Create A <br /> <b> New Company</b>...</p>
        </div>

        <div id="c" class="col-md-4">
            <a id="a" class=" btn btn-success">Create New company</a>
            <div id="companybox" class="col-md-4">
                <form id="form">
                    <fieldset id="title">
                        <div class="row">
                            <br />
                            <div class="col-md-4">

                                <br /> <p id="p1">Enter New CompanyName</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <input placeholder="Company Name" id="company" type="text" class="form-control" name="txt1" required />
                        </div>
                        <div class="form-group">
                            <a href="#" class="btn btn-success" id="Save">Save Company</a>
                        </div>

                    </fieldset>
                </form>

                <button class="btn btn-success" id="cancel1">cancel</button>

            </div>
        </div>
        @*<div class="col-md-4">
                <p class="btn btn-" id="p1"> Click This Button to Create A <br /> <b> AssignRoles To Users</b>...</p>
            </div>*@

        <br />
        <br /><br />
        <br />
        <br />
        <br />
        <br />
        <br />


    </div>
    <hr />
    <div class="row">

        <div class="col-md-4">
            <p id="p1"><span class="glyphicon glyphicon-share-alt"></span> &nbsp;&nbsp;&nbsp; Click This Button to Assign  <b>Admin's</b> to <b>Company</b>...</p>
        </div>
        <br />
        @*<div class="col-md-4">@Html.ActionLink("AssignRoles To Users", "AssignRolesToUsers", "Base", new { @class = "btn btn-success" })</div>*@
        <div class="col-md-4">@Html.ActionLink("Assign Admin's to company", "AssignUsersToCompany", "Base", new { @class = "btn btn-success" })</div>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
    </div>
    <script>
        $(document).ready(function () {
            $('#c').show();
            $('#companybox ').hide();
            $(".slide_box").init_slide();
        });
        $('.selectall').click(function () {
            if ($(this).is(':checked')) {
                $('div input').attr('checked', true);
            } else {
                $('div input').attr('checked', false);
            }
        });
        $("#c").click(function () {
            $('#a').hide();
            $('#companybox ').show();
        })
        $("#cancel1").click(function () {

            window.location.href = "/Base/MasterPage";
        })

        $("#Save").click(function () {

            var t = $('#company').val();
            $(".error").remove();
            if (t.length < 1) {

                $('#company').after('<span class="error">please enter CompanyName</span>');
            }
            else {
                $.ajax({
                    type: "POST",
                    url: "/Base/SaveCompany?txt1=" + t,
                    success: function (result) {
                        if (result == true) {
                            window.alert('Company created successfully');

                            window.location.href = "/Base/MasterPage";
                        }
                    }
                })
            }
        })
    </script>

</body>
</html>